### ISSUE TITLE
Can I add proxy?

### ISSUE THREAD

**Issue by stirp** [sigoden/apitest#4]
I'd like to use apitest for CI. But My CI system is isolated from running env, but socket or http proxy is available. Is there a way to add proxy for apitest?

**Comment by sigoden** [comment]
Proxy will be added in the next version

```
@client({
  options: {
      proxy: "http://user:pass@localhost:8080"
    }
})
```

You can also define your proxy using the conventional `HTTP_RPOXY` and  `HTTPS_RPOXY` environment variables
