### ISSUE TITLE
how can i show the req res info, even test pass? 

### ISSUE THREAD

**Issue by wenshunchen3** [sigoden/apitest#8]
![image](https://user-images.githubusercontent.com/74223320/122513162-96b52080-d03c-11eb-80a2-131084c33be3.png)

**Comment by sigoden** [comment]
Set the value of `run.dump` to true
```
{
  test1: { @client("echo")
    req: {
    },
    run: {
      dump: true,
    }
  }
}
```

**Comment by wenshunchen3** [comment]
> Set the value of `run.dump` to true
> 
> ```
> {
>   test1: { @client("echo")
>     req: {
>     },
>     run: {
>       dump: true,
>     }
>   }
> }
> ```

thks a lot.

**Comment by sigoden** [comment]
```
    run: {
      dump: true,
    }
```

You only need to add this parts to your testcase.
